language: rust
rust:
- stable
- beta
- nightly
os:
- linux
- osx
script:
- cargo build --verbose
- cargo test --verbose
- scripts/travis-publish.sh
notifications:
  email: false
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: ./target/release/release-party-br-*
  api_key:
    secure: qjUCYAeEPA3LO1Q149IEPJ/MRjdKyCef7cKdby7Q+PEJnMuYFZwM+q1FQy7wYXgIEPFRY9aLof2xJmA8+WZdbuoZsKl1yc5KOb7n3Cmd1uR8FGt7Wmg9Y+ljRRuX0j5i8o1/+X2wbFHoTBoT9Ou/cq2LXAMeFmzORS+XqRCKJRg7Sl6qHga5SckE5BfJ+bL6z8BV95Mrde5X8dmBQmvWPeYttY0wvfrja1ipflL/ypT6cIbKmOgM4g1YcEJTzn0r/uFOWrkWw9wXRW02pg4bPZEtP+2kseQ+lBQk6/g4Njn4n+M3/34fgMQBBIjk2m0dK/8qqGq51ODWVQ3sDKvUCjVfyLQbHf1BpvSvDTQ1JCkiYQ3LXTXNy6Q3LFzGb9ohvfpX/wPJC/R027wTDhYhlIgcdMhIyonjUrw69mMrfY6Ish8enhCxfmgcm67JAW7d/tzYXEVeP+6co6uSEdyTxA4MK0U2LQxdehDxUM9m4p/LlVIrMBN/5ADHOEiEinwnoeMOtsCaCdmXh2qqoPKRvlIhRulgWaqjEKD9uy/by5cXLoyuLVr/WR2WKgse+aqbh7Cuz2uAWt6epoxD3x1sUFQScBofWQC/2f6Jvo7aW+XmaXE/NIEm+DoXrFpokNruBRqB90L0EZpof9mkbukcz6TjPXsn8HcYSx/sofViiIQ=
  on:
    repo: matthewkmayer/release-party-BR
    tags: true
    condition: ("$TRAVIS_OS_NAME" == "linux" || "$TRAVIS_OS_NAME" == "osx" ) && "$TRAVIS_RUST_VERSION" == "stable"