[package]
name = "release-party-br"
version = "0.2.0"
authors = ["Matthew Mayer <matthewkmayer@gmail.com>"]

[dependencies]
reqwest = "0.7.3"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
toml = "0.4.1"
clap = "2.24.2"
clippy = {version = "*", optional = true}

[features]
default = []