[package]
name = "release-party-br"
version = "0.1.0"
authors = ["Matthew Mayer <matthewkmayer@gmail.com>"]

[dependencies]
reqwest = "0.4.0"
serde = "0.9.9"
serde_json = "0.9.8"
serde_derive = "0.9"
toml = "0.3.0"